# Generated by Django 2.2.5 on 2019-12-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, upload_to='banner_photos', verbose_name='배너 이미지')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
