# Generated by Django 2.2.5 on 2019-10-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191024_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='cheak_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='cheak_out',
            new_name='check_out',
        ),
    ]
