# Generated by Django 2.2.5 on 2019-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20191025_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='chech_out',
            new_name='check_out',
        ),
    ]
